### ISSUE TITLE
Bank Angle on ND Broken in 4.0 & "Wallowing" to track back.

### ISSUE THREAD

**Issue by tomvachon** [Delta-Simulations/MSFS-C-17#6]
The HUD bank angle indicator works, but ND doesn't.  Also the AP is again going left and right of track which was fixed in 3.5.1.

**Comment by Destroyer121** [comment]
This was an issue with caging the standby horizon. Try hitting the cage button again and it should resolve itself.

**Comment by Destroyer121** [comment]
@tomvachon Can you confirm that this no longer occurs with V4.1.5?
